module.exports = (->


  # see dom_graph.coffee for a 'tree_hash' example;
  # those methods are generated by entry.coffee onto StaticDom.
  # 'parent' is only used internally during recursion.
  @build_dom_methods = (tree_hash, parent, memo={}) =>
    for name,opts of tree_hash
      memo[name] = @build_fn(memo, name, opts.selector, parent)
      if opts.children
        @build_dom_methods(opts.children, name, memo) 
    memo

  @build_fn = (memo, name, selector, parent) =>
    (allow_cache = true) =>
      get_val = =>
        if parent then memo[parent]().find(selector) else $(selector)
      if allow_cache then (memo["_#{name}"] ||= get_val()) else get_val()

  this
).apply {}